import SettingsScope from './SettingsScope';

type Topic =
  | 'settings:update'
  | 'settings:toggle'
  | 'twitch:stream_online'
  | 'twitch:stream_offline'
  | 'twitch:channel_update'
  | 'twitch:follow'
  | 'twitch:subscription'
  | 'twitch:subscription_gift'
  | 'twitch:subscription_message'
  | 'twitch:subscription_end'
  | 'twitch:cheer'
  | 'twitch:charity_start'
  | 'twitch:charity_stop'
  | 'twitch:charity_donation'
  | 'twitch:charity_progress'
  | 'twitch:ban'
  | 'twitch:unban'
  | 'twitch:shield_begin'
  | 'twitch:shield_end'
  | 'twitch:mod_add'
  | 'twitch:mod_remove'
  | 'twitch:raid'
  | 'twitch:raid_to'
  | 'twitch:reward_add'
  | 'twitch:reward_update'
  | 'twitch:reward_remove'
  | 'twitch:redemption'
  | 'twitch:redemption_update'
  | 'twitch:poll_begin'
  | 'twitch:poll_progress'
  | 'twitch:poll_end'
  | 'twitch:prediction_begin'
  | 'twitch:prediction_progress'
  | 'twitch:prediction_lock'
  | 'twitch:prediction_end'
  | 'twitch:goal_begin'
  | 'twitch:goal_progress'
  | 'twitch:goal_end'
  | 'twitch:hype_train_begin'
  | 'twitch:hype_train_progress'
  | 'twitch:hype_train_end'
  | 'twitch:shoutout_create'
  | 'twitch:shoutout_receive';

export const TopicAuthorization: { [key in Topic]: SettingsScope | null } = {
  'settings:toggle': null,
  'settings:update': null,
  'twitch:ban': 'twitch:ban',
  'twitch:channel_update': 'twitch:channel_update',
  'twitch:charity_donation': 'twitch:charity',
  'twitch:charity_progress': 'twitch:charity',
  'twitch:charity_start': 'twitch:charity',
  'twitch:charity_stop': 'twitch:charity',
  'twitch:cheer': 'twitch:cheer',
  'twitch:follow': 'twitch:follow',
  'twitch:goal_begin': 'twitch:goal',
  'twitch:goal_end': 'twitch:goal',
  'twitch:goal_progress': 'twitch:goal',
  'twitch:hype_train_begin': 'twitch:hype_train',
  'twitch:hype_train_end': 'twitch:hype_train',
  'twitch:hype_train_progress': 'twitch:hype_train',
  'twitch:mod_add': 'twitch:mod',
  'twitch:mod_remove': 'twitch:mod',
  'twitch:poll_begin': 'twitch:poll',
  'twitch:poll_end': 'twitch:poll',
  'twitch:poll_progress': 'twitch:poll',
  'twitch:prediction_begin': 'twitch:prediction',
  'twitch:prediction_end': 'twitch:prediction',
  'twitch:prediction_lock': 'twitch:prediction',
  'twitch:prediction_progress': 'twitch:prediction',
  'twitch:raid': 'twitch:raid',
  'twitch:raid_to': 'twitch:raid',
  'twitch:redemption': 'twitch:channel_points',
  'twitch:redemption_update': 'twitch:channel_points',
  'twitch:reward_add': 'twitch:channel_points',
  'twitch:reward_remove': 'twitch:channel_points',
  'twitch:reward_update': 'twitch:channel_points',
  'twitch:shield_begin': 'twitch:shield',
  'twitch:shield_end': 'twitch:shield',
  'twitch:shoutout_create': 'twitch:shoutout',
  'twitch:shoutout_receive': 'twitch:shoutout',
  'twitch:stream_offline': null,
  'twitch:stream_online': null,
  'twitch:subscription': 'twitch:subscription',
  'twitch:subscription_end': 'twitch:subscription',
  'twitch:subscription_gift': 'twitch:subscription',
  'twitch:subscription_message': 'twitch:subscription',
  'twitch:unban': 'twitch:ban',
};

export default Topic;
